sales_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: RDTEAM
      warehouse: NAKAMURA_WH
      database: STARTER
      schema: SALES
      account: ''
      user: 'RIHITO_NAKAMURA'
    prod:
      type: snowflake
      role: RDTEAM
      warehouse: NAKAMURA_WH
      database: STARTER
      schema: SALES
      account: ''
      user: 'RIHITO_NAKAMURA'
