sales_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: EXTURE-PRACTICE 
      role: RDTEAM
      warehouse: NAKAMURA_WH
      database: STARTER
      schema: SALES
      user: RIHITO_NAKAMURA
      password: Rihito@Nakamura_123456
    prod:
      type: snowflake
      role: RDTEAM
      warehouse: NAKAMURA_WH
      database: STARTER
      schema: SALES
      account: ''
      user: 'RIHITO_NAKAMURA'
