name: dbt-docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dbt-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Overwrite profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOL
          my_project:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: EXTURE-PRACTICE
                user: RIHITO_NAKAMURA
                password: ${{ secrets.DBT_PASSWORD }}
                authenticator: username_password_mfa
                client_session_keep_alive: True
                role: RDTEAM
                database: STARTER
                warehouse: NAKAMURA_WH
                schema: SALES
          EOL

      - name: Run dbt
        run: |
          dbt deps
          dbt compile  
          dbt docs generate

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target
          publish_branch: gh-pages
          keep_files: true
          enable_jekyll: false
